// @ts-nocheck
// All UI strings in Spanish (es) and English (en).
// Values used in innerHTML should use &amp; not bare &.

const STRINGS = {
  es: {
    heroSubtitle: "La ciudad colonial más colorida de México — historia, mercados, callejuelas y vida nocturna",
    searchPlaceholder: 'Prueba "cata de mezcal con amigos" o "caminata fácil con vistas"…',
    searchBtn: "Encuéntrame algo",
    searchClear: "Limpiar ×",
    filterAll: "Todo",
    filterCulture: "🏛️ Historia &amp; Cultura",
    filterFood: "🌮 Comida &amp; Mercados",
    filterOutdoor: "🌄 Naturaleza",
    filterNightlife: "🎭 Vida Nocturna",
    filterFirst: "🌟 Primer Viaje",
    sortLabel: "Ordenar por",
    sortDefault: "Orden predeterminado",
    sortRating: "Mejor calificado",
    sortActivities: "Más actividades",
    sortEasiest: "Más fácil primero",
    sortHardest: "Más difícil primero",
    vibeLabel: "¿Cuál es tu plan de hoy?",
    vibeCulture: "🏛️ Historia",
    vibeFood: "🌮 Comer",
    vibeOutdoor: "🌄 Naturaleza",
    vibeNightlife: "🎭 Festejo",
    featuredEyebrow: "⭐ Destacado de hoy",
    catCulture: "🏛️ Historia &amp; Cultura",
    catFood: "🌮 Comida &amp; Mercados",
    catOutdoor: "🌄 Exterior &amp; Naturaleza",
    catNightlife: "🎭 Vida Nocturna &amp; Festivales",
    catFirst: "🌟 Imperdibles para Primer Viaje",
    seeAll: "Ver todos &#8599;",
    subFestivos: "🎭 Festivales &amp; Eventos",
    subBares: "🎵 Bares &amp; Música en Vivo",
    cardMap: "Ver en Mapa &#8599;",
    cardRate: "&#9733; Calificar",
    cardSave: "Guardar en mi viaje",
    cardUnsave: "Guardado — quitar",
    firstTimerBadge: "🌟 Imperdible",
    insightsTitle: "Insights",
    statDests: "destinos",
    statAvg: "calificación promedio",
    statTop: "Top actividad:",
    statTags: "tags promedio / destino",
    freqTitle: "Distribución de Actividades",
    tipsTitle: "Tips Rápidos",
    tips: [
      "🕐 <strong>Mejor época:</strong> Oct–Nov (Cervantino y Día de Muertos) o Semana Santa. Evita el verano si odias el calor.",
      "🚌 <strong>Cómo llegar:</strong> Vuela a León (BJX) y toma un camión o taxi al Centro de Guanajuato — 30–40 min.",
      "🚶 <strong>Camina todo:</strong> El centro es peatonal. Perderte en las callejuelas es parte de la experiencia.",
      "⛏️ <strong>Minas:</strong> La visita a Valenciana incluye guía; lleva ropa abrigadora — adentro hace frío.",
      "🌮 <strong>Come local:</strong> Desayuna enchiladas mineras en el Mercado Hidalgo — el mejor precio de la ciudad.",
      "🎭 <strong>Callejoneada:</strong> Salen del Jardín Unión la mayoría de las noches; negocia el precio directo con la estudiantina.",
    ],
    footerMain: "Trip Vibes Guanajuato &mdash; Guía de Viaje 2026",
    footerSub: "Siempre verifica horarios y precios directamente con cada sitio antes de visitar.",
    recoTitle: "También Te Puede Gustar",
    communityTitle: "Calificación Comunitaria",
    noRatings: "Sin calificaciones — ¡sé el primero!",
    rateTitle: "Califica Este Lugar",
    commentTitle: "Deja un Comentario",
    commentNamePh: "Tu nombre (opcional)",
    commentBodyPh: "Comparte tu experiencia en este lugar...",
    commentSubmit: "Publicar",
    commentsTitle: "Lo Que Dicen los Viajeros",
    commentsLoading: "Cargando...",
    commentsEmpty: "Sin comentarios todavía. ¡Comparte tu experiencia!",
    ratingThanks: "¡Gracias por tu calificación!",
    ratingError: "No se pudo guardar. Inténtalo de nuevo.",
    searchNoResults: 'Sin resultados — prueba "mezcal", "minas", "festival" o "vistas"',
    searchNoResultsText: "Ningún destino coincide. Intenta con otras palabras.",
    explore: "Explorar &#8599;",
    savedCount: "lugar(es) en mi viaje",
    printBtn: "🖨️ Imprimir itinerario",
    printTitle: "Mi Itinerario — Guanajuato",
    // Day labels for featured pick
    daySun: "Recomendación del Domingo",
    dayMon: "Destino del Lunes",
    dayTue: "Destino del Martes",
    dayWed: "Destino del Miércoles",
    dayThu: "Destino del Jueves",
    dayFri: "Destino del Viernes",
    dayFriNight: "Pick de Viernes por la Noche",
    daySat: "Destino del Sábado",
    daySatMorn: "Pick Mañanero del Sábado",
  },

  en: {
    heroSubtitle: "Mexico's most colorful colonial city — history, markets, alleyways &amp; nightlife",
    searchPlaceholder: 'Try "mezcal tasting with friends" or "easy hike with a great view"…',
    searchBtn: "Find for me",
    searchClear: "Clear ×",
    filterAll: "All",
    filterCulture: "🏛️ History &amp; Culture",
    filterFood: "🌮 Food &amp; Markets",
    filterOutdoor: "🌄 Nature",
    filterNightlife: "🎭 Nightlife",
    filterFirst: "🌟 First Timers",
    sortLabel: "Sort by",
    sortDefault: "Default order",
    sortRating: "Highest rated",
    sortActivities: "Most activities",
    sortEasiest: "Easiest first",
    sortHardest: "Hardest first",
    vibeLabel: "What's your vibe today?",
    vibeCulture: "🏛️ History",
    vibeFood: "🌮 Eat",
    vibeOutdoor: "🌄 Nature",
    vibeNightlife: "🎭 Nightlife",
    featuredEyebrow: "⭐ Featured today",
    catCulture: "🏛️ History &amp; Culture",
    catFood: "🌮 Food &amp; Markets",
    catOutdoor: "🌄 Outdoor &amp; Nature",
    catNightlife: "🎭 Nightlife &amp; Festivals",
    catFirst: "🌟 First Timer's Must-Sees",
    seeAll: "See all &#8599;",
    subFestivos: "🎭 Festivals &amp; Events",
    subBares: "🎵 Bars &amp; Live Music",
    cardMap: "View on Map &#8599;",
    cardRate: "&#9733; Rate",
    cardSave: "Save to my trip",
    cardUnsave: "Saved — remove",
    firstTimerBadge: "🌟 Must See",
    insightsTitle: "Insights",
    statDests: "destinations",
    statAvg: "avg rating",
    statTop: "Top activity:",
    statTags: "avg tags / dest",
    freqTitle: "Activity Distribution",
    tipsTitle: "Quick Tips",
    tips: [
      "🕐 <strong>Best time:</strong> Oct–Nov (Cervantino &amp; Day of the Dead) or Easter Week. Avoid July–Aug if you hate heat.",
      "🚌 <strong>Getting there:</strong> Fly to León (BJX), then take a bus or taxi to Centro — 30–40 min.",
      "🚶 <strong>Walk everything:</strong> The centro is pedestrian-only. Getting lost in the alleys is part of the experience.",
      "⛏️ <strong>Mine visits:</strong> Valenciana includes a guide; wear layers — it's cold underground.",
      "🌮 <strong>Eat local:</strong> Breakfast enchiladas mineras at Mercado Hidalgo — best price and best flavor in town.",
      "🎭 <strong>Callejoneada:</strong> They leave from Jardín Unión most evenings — negotiate the price directly with the band.",
    ],
    footerMain: "Trip Vibes Guanajuato &mdash; Travel Guide 2026",
    footerSub: "Always verify hours and prices directly with each venue before visiting.",
    recoTitle: "You Might Also Like",
    communityTitle: "Community Rating",
    noRatings: "No ratings yet — be the first!",
    rateTitle: "Rate This Place",
    commentTitle: "Leave a Comment",
    commentNamePh: "Your name (optional)",
    commentBodyPh: "Share your experience at this place...",
    commentSubmit: "Post Comment",
    commentsTitle: "What Travelers Say",
    commentsLoading: "Loading...",
    commentsEmpty: "No comments yet. Share your experience!",
    ratingThanks: "Thanks for your rating!",
    ratingError: "Could not save rating. Try again.",
    searchNoResults: 'No matches — try "mezcal", "mine", "festival" or "views"',
    searchNoResultsText: "No destinations matched. Try different words.",
    explore: "Explore &#8599;",
    savedCount: "saved to my trip",
    printBtn: "🖨️ Print itinerary",
    printTitle: "My Guanajuato Itinerary",
    // Day labels for featured pick
    daySun: "Sunday Pick",
    dayMon: "Monday Pick",
    dayTue: "Tuesday Pick",
    dayWed: "Midweek Pick",
    dayThu: "Thursday Pick",
    dayFri: "Friday Pick",
    dayFriNight: "Friday Night Pick",
    daySat: "Saturday Pick",
    daySatMorn: "Saturday Morning Pick",
  },
};
